import React from "react";
const K="#111111";
const Floor=({w,h})=><line x1={w*.04} y1={h*.76} x2={w*.96} y2={h*.76}/>;
const Label=({w,h,text})=><text x={w*.5} y={h*.24} textAnchor="middle" fontFamily="Arial" fontWeight="700" fontSize={Math.max(18,w*.035)} fill={K}>{text}</text>;

export const Environment=({id="white_stage",width=720,height=1280,frame=0})=>{
 const drift=Math.sin(frame/30)*8,op=.14;
 if(id==="bank_counter"||id==="hospital_billing"||id==="collections_office"||id==="tax_office") return <g opacity={op} stroke={K} strokeWidth="4" fill="none"><Floor w={width} h={height}/><rect x={width*.08} y={height*.58} width={width*.84} height={height*.14} rx="18"/><rect x={width*.34} y={height*.34} width={width*.32} height={height*.16} rx="12"/><Label w={width} h={height} text={id.replaceAll("_"," ").toUpperCase()}/></g>;
 if(id==="airport_lounge"||id==="hotel_lobby"||id==="baggage_claim") return <g opacity={op} stroke={K} strokeWidth="4" fill="none" transform={`translate(${drift} 0)`}><Floor w={width} h={height}/><path d={`M${width*.12} ${height*.64} q${width*.08} -${height*.08} ${width*.16} 0 v${height*.07} h-${width*.16}z M${width*.58} ${height*.64} q${width*.08} -${height*.08} ${width*.16} 0 v${height*.07} h-${width*.16}z`}/><rect x={width*.33} y={height*.30} width={width*.34} height={height*.16} rx="14"/><Label w={width} h={height} text={id.replaceAll("_"," ").toUpperCase()}/></g>;
 if(id==="retail_store"||id==="grocery_checkout"||id==="luxury_store") return <g opacity={op} stroke={K} strokeWidth="4" fill="none"><Floor w={width} h={height}/>{[.12,.38,.64].map((x,i)=><g key={i}><rect x={width*x} y={height*.35} width={width*.2} height={height*.28}/><line x1={width*x} y1={height*.45} x2={width*(x+.2)} y2={height*.45}/><line x1={width*x} y1={height*.55} x2={width*(x+.2)} y2={height*.55}/></g>)}<Label w={width} h={height} text={id.replaceAll("_"," ").toUpperCase()}/></g>;
 if(id==="apartment"||id==="college_dorm"||id==="office_cubicle"||id==="coffee_shop") return <g opacity={op} stroke={K} strokeWidth="4" fill="none"><Floor w={width} h={height}/><rect x={width*.1} y={height*.38} width={width*.3} height={height*.26}/><rect x={width*.58} y={height*.54} width={width*.26} height={height*.15} rx="18"/><line x1={width*.26} y1={height*.38} x2={width*.26} y2={height*.64}/><Label w={width} h={height} text={id.replaceAll("_"," ").toUpperCase()}/></g>;
 if(id==="airplane_cabin") return <g opacity={op} stroke={K} strokeWidth="4" fill="none"><Floor w={width} h={height}/>{[.1,.38,.66].map((x,i)=><g key={i}><rect x={width*x} y={height*.48} width={width*.18} height={height*.18} rx="26"/><ellipse cx={width*(x+.09)} cy={height*.36} rx={width*.07} ry={height*.06}/></g>)}<Label w={width} h={height} text="AIRPLANE CABIN"/></g>;
 if(id==="gas_station") return <g opacity={op} stroke={K} strokeWidth="4" fill="none"><Floor w={width} h={height}/><rect x={width*.12} y={height*.4} width={width*.2} height={height*.3}/><rect x={width*.68} y={height*.4} width={width*.2} height={height*.3}/><line x1={width*.06} y1={height*.3} x2={width*.94} y2={height*.3}/><Label w={width} h={height} text="GAS STATION"/></g>;
 if(id==="car_dealership") return <g opacity={op} stroke={K} strokeWidth="4" fill="none"><Floor w={width} h={height}/><path d={`M${width*.18} ${height*.62} q${width*.14} -${height*.12} ${width*.28} 0 h${width*.08} v${height*.06} h-${width*.4}z`}/><circle cx={width*.26} cy={height*.69} r={width*.035}/><circle cx={width*.52} cy={height*.69} r={width*.035}/><Label w={width} h={height} text="CAR DEALERSHIP"/></g>;
 if(id==="courtroom_metaphor") return <g opacity={op} stroke={K} strokeWidth="4" fill="none"><Floor w={width} h={height}/><rect x={width*.31} y={height*.43} width={width*.38} height={height*.22}/><line x1={width*.5} y1={height*.3} x2={width*.5} y2={height*.43}/><Label w={width} h={height} text="COURTROOM"/></g>;
 if(id==="casino") return <g opacity={op} stroke={K} strokeWidth="4" fill="none"><Floor w={width} h={height}/>{[.17,.43,.69].map((x,i)=><rect key={i} x={width*x} y={height*.4} width={width*.14} height={height*.24} rx="18"/>)}<circle cx={width*.5} cy={height*.31} r={width*.09}/><Label w={width} h={height} text="CASINO"/></g>;
 if(id==="bank_vault") return <g opacity={op} stroke={K} strokeWidth="4" fill="none"><Floor w={width} h={height}/><circle cx={width*.5} cy={height*.5} r={width*.22}/><circle cx={width*.5} cy={height*.5} r={width*.12}/><line x1={width*.38} y1={height*.5} x2={width*.62} y2={height*.5}/><Label w={width} h={height} text="BANK VAULT"/></g>;
 if(id==="debt_dungeon"||id==="subscription_maze") return <g opacity={op} stroke={K} strokeWidth="5" fill="none" transform={`translate(${drift} 0)`}><Floor w={width} h={height}/><path d={`M${width*.08} ${height*.32} V${height*.7} H${width*.28} V${height*.42} H${width*.48} V${height*.68} H${width*.72} V${height*.38} H${width*.92}`}/><Label w={width} h={height} text={id==="debt_dungeon"?"DEBT DUNGEON":"SUBSCRIPTION MAZE"}/></g>;
 if(id==="rewards_factory") return <g opacity={op} stroke={K} strokeWidth="4" fill="none"><Floor w={width} h={height}/><rect x={width*.08} y={height*.55} width={width*.84} height={height*.08}/>{[.2,.45,.7].map((x,i)=><circle key={i} cx={width*x} cy={height*.59} r={width*.035}/>)}<path d={`M${width*.2} ${height*.55} v-${height*.16} h${width*.12} v${height*.16} M${width*.62} ${height*.55} v-${height*.2} h${width*.12} v${height*.2}`}/><Label w={width} h={height} text="REWARDS FACTORY"/></g>;
 if(id==="credit_score_lab") return <g opacity={op} stroke={K} strokeWidth="4" fill="none"><Floor w={width} h={height}/><circle cx={width*.5} cy={height*.48} r={width*.15}/><line x1={width*.5} y1={height*.48} x2={width*.58} y2={height*.4}/><rect x={width*.18} y={height*.42} width={width*.15} height={height*.22}/><Label w={width} h={height} text="CREDIT SCORE LAB"/></g>;
 if(id==="interest_treadmill") return <g opacity={op} stroke={K} strokeWidth="5" fill="none"><Floor w={width} h={height}/><rect x={width*.2} y={height*.58} width={width*.6} height={height*.08} rx="22"/><line x1={width*.68} y1={height*.58} x2={width*.76} y2={height*.4}/><Label w={width} h={height} text="INTEREST TREADMILL"/></g>;
 if(id==="finance_metaphor_world"||id==="online_checkout_world"||id==="stock_exchange_parody") return <g opacity=".12" stroke={K} strokeWidth="4" fill="none" transform={`translate(${drift} 0)`}><circle cx={width*.22} cy={height*.36} r={width*.12}/><circle cx={width*.78} cy={height*.5} r={width*.17}/><path d={`M0 ${height*.72} Q${width*.25} ${height*.58} ${width*.5} ${height*.72} T${width} ${height*.72}`}/><Label w={width} h={height} text={id.replaceAll("_"," ").toUpperCase()}/></g>;
 return <g opacity=".08" stroke={K} strokeWidth="3" fill="none"><Floor w={width} h={height}/></g>;
};