import React from "react";
import {interpolate} from "remotion";
const K="#111",W="#fff",R="#e53935",G="#16a34a",Y="#b7791f",L="#eee",C={extrapolateLeft:"clamp",extrapolateRight:"clamp"};
const I=(v,a,b,x,y)=>interpolate(v,[a,b],[x,y],C);
const D=[
["THE FEE NOTICE LANDS.","$695 EXAMPLE FEE","EXAMPLE PREMIUM-CARD FEE","DAVE","letter",K],
["DAVE DOES THE DOUBLE-TAKE.","$695. AGAIN?","FEE ≠ AUTOMATIC VALUE","DAVE","card",R],
["ENTER CHAD.","SPEND $80","CHAD CALLS THIS A DEAL.","CHAD","offer",K],
["THE CATCH.","“SAVE” $20","THE CREDIT REQUIRES SPEND.","CHAD","offer",G],
["NET SPEND.","$80 − $20 = $60","YOU STILL SPENT $60.","DUO","math",R],
["POINTS MONK INTERRUPTS.","CREDIT ≠ FREE","COUNT ONLY REAL VALUE.","POINTS MONK","x",R],
["DO THE ACTUAL MATH.","$60 STILL LEFT","SAVINGS CAN CREATE SPEND.","POINTS MONK","math",R],
["DAVE FINALLY SEES IT.","− $60 CASH","DON’T BUY VALUE YOU DIDN’T WANT.","DAVE","cash",R],
["COMPARE VALUE TO THE FEE.","REAL VALUE vs FEE","COUNT BENEFITS YOU’D BUY ANYWAY.","POINTS MONK","scale",Y],
["VALUE WINS?","MAYBE KEEP IT","NET VALUE SHOULD CLEAR THE FEE.","POINTS MONK","good",G],
["VALUE LOSES?","RE-EVALUATE","DON’T FORCE SPEND TO JUSTIFY A CARD.","POINTS MONK","bad",R],
["ONE RULE.","VALUE > FEE","COUNT REAL VALUE. IGNORE THE FLEX.","DUO","check",G]
];
const Person=({x,y,name,p,face})=>{const a=Math.sin((p+name.length)*6)*25,m=face==="wow"?"M-8 -58a8 10 0 1 0 16 0a8 10 0 1 0-16 0":face==="smile"?"M-16 -67Q0 -50 16 -67":face==="mad"?"M-16 -58Q0 -71 16 -58":"M-12 -58L12 -58";return <g transform={`translate(${x} ${y}) scale(1.3)`} stroke={K} strokeWidth="7" fill="none" strokeLinecap="round"><text y="-140" textAnchor="middle" fill={K} stroke="none" fontFamily="Arial" fontWeight="900" fontSize="21">{name}</text><circle cy="-82" r="34" fill={W}/><circle cx="-11" cy="-90" r="4" fill={K} stroke="none"/><circle cx="11" cy="-90" r="4" fill={K} stroke="none"/><path d={m}/><line y1="-48" y2="88"/><line y1="-4" x2={-68-a} y2="32"/><line y1="-4" x2={68+a} y2="-4"/><line y1="88" x2="-52" y2="175"/><line y1="88" x2="52" y2="175"/></g>};
const Prop=({kind,p})=>{if(kind==="scale")return <g transform="translate(360 505)"><line x1="-210" x2="210" stroke={K} strokeWidth="8"/><line y1="-80" y2="80" stroke={K} strokeWidth="8"/><circle cx={I(p,0,1,-170,125)} cy="-35" r="28" fill={W} stroke={Y} strokeWidth="8"/></g>;if(kind==="good"||kind==="bad"){let q=kind==="good"?.86:.34,z=kind==="good"?G:R;return <g><rect x="90" y="430" width="540" height="70" rx="35" fill={L} stroke={K} strokeWidth="6"/><rect x="90" y="430" width={540*I(p,0,1,0,q)} height="70" rx="35" fill={z}/></g>}if(kind==="x")return <g stroke={R} strokeWidth="20"><line x1="250" y1="430" x2="470" y2="650"/><line x1="470" y1="430" x2="250" y2="650"/></g>;if(kind==="check")return <path d="M150 550L300 660L585 440" fill="none" stroke={G} strokeWidth="22" strokeLinecap="round"/>;let s=kind==="letter"?"ANNUAL FEE|$695":kind==="card"?"$695 / YEAR":kind==="offer"?"SPEND $80|SAVE $20":kind==="math"?"$80 − $20|= $60":kind==="cash"?"− $60":"";return <g transform={`translate(360 510) scale(${I(p,0,.18,.75,1)}) rotate(${I(p,0,1,-9,3)})`}><rect x="-145" y="-92" width="290" height="184" rx="20" fill={W} stroke={K} strokeWidth="7"/>{s.split("|").map((v,i)=><text key={v} y={-15+i*55} textAnchor="middle" fill={kind==="cash"?R:K} fontFamily="Arial" fontWeight="1000" fontSize="35">{v}</text>)}</g>};
export const V7Visual=({frame})=>{const t=frame/24,n=Math.min(11,Math.floor(t/2.5)),p=(t-n*2.5)/2.5,[h,chip,foot,who,kind,color]=D[n],face=n===1||n===7?"wow":n===2||n===3||n===9||n===11?"smile":n===5||n===10?"mad":"flat";return <div style={{position:"absolute",inset:0,background:W,transform:`translateX(${[0,-7,6,-5,7,-6,5,-7,6,-5,5,0][n]}px) scale(${1+.02*Math.sin(p*Math.PI)})`}}><div style={{position:"absolute",top:52,left:44,right:44,textAlign:"center",fontFamily:"Arial",fontWeight:1000,fontSize:53,lineHeight:.95,color}}>{h}</div><svg width="720" height="1280"><Prop kind={kind} p={p}/>{who==="DAVE"&&<Person x={180} y={840} name="DAVE" p={p} face={face}/>} {who==="CHAD"&&<Person x={540} y={840} name="CHAD" p={p} face={face}/>} {who==="POINTS MONK"&&<Person x={540} y={840} name="POINTS MONK" p={p} face={face}/>} {who==="DUO"&&<><Person x={165} y={850} name="DAVE" p={p} face="smile"/><Person x={555} y={850} name="POINTS MONK" p={p} face="smile"/></>}</svg><div style={{position:"absolute",top:770,left:120,right:120,padding:18,border:`6px solid ${color}`,borderRadius:22,background:W,textAlign:"center",fontFamily:"Arial",fontWeight:1000,fontSize:34,color}}>{chip}</div><div style={{position:"absolute",bottom:72,left:48,right:48,textAlign:"center",fontFamily:"Arial",fontWeight:900,fontSize:29,color:K}}>{foot}</div></div>};
